/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CasaEscenario.glb 
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ onZoomVitrina, ...props }) {
  const { nodes, materials } = useGLTF('/models/CasaEscenario.glb')
  
  // 🟦 Estado para ocultar únicamente las capas principales/frontales de la fachada
  const [ocultarPrincipales, setOcultarPrincipales] = useState(false)

  const handleClick = (e) => {
    e.stopPropagation() // Evita que el clic se propague a los planos traseros
    setOcultarPrincipales(true) // Oculta la parte frontal de la casa
    if (onZoomVitrina) onZoomVitrina() // Desata la animación de acercamiento en Experience
  }

  const handlePointerOver = (e) => {
    e.stopPropagation()
    document.body.style.cursor = 'pointer'
  }
  const handlePointerOut = (e) => {
    e.stopPropagation()
    document.body.style.cursor = 'auto'
  }

  return (
    <group {...props} dispose={null}>
       {/* ❌ Plano 1: Cornisa y árboles (Se oculta para permitir el paso de la cámara) */}
       <group position={[0, 0.771, 0]} scale={[1, 1.277, 1]} visible={!ocultarPrincipales}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials.cardboard} />
      </group> 

       {/* ❌ Plano 2: Fachada de la casa (Se oculta) */}
       <mesh visible={!ocultarPrincipales} geometry={nodes.Plane012.geometry} material={materials['Material.001']} />
      <mesh visible={!ocultarPrincipales} geometry={nodes.Plane012_1.geometry} material={materials.cardboard} /> 
      
      {/* ❌ Plano 3: Frontal casa (Se oculta) */}
      <mesh visible={!ocultarPrincipales} geometry={nodes.Plane008.geometry} material={materials.cardboard} />
      <mesh visible={!ocultarPrincipales} geometry={nodes.Plane008_1.geometry} material={materials.Material} />
       
      <group position={[0, 0, -0.565]}>
        <mesh geometry={nodes.Plane016.geometry} material={materials.pared} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.cardboard} />
      </group>
      
      {/* 🌌 CAPAS DE FONDO (Se mantienen totalmente visibles) */}
      <mesh geometry={nodes.Cielo.geometry} material={materials.fondo} position={[-0.784, 1.074, -6.79]} scale={0.648} />
      <mesh geometry={nodes['35Macetas'].geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cielo001.geometry} material={materials['fondo.001']} position={[-0.784, 1.074, -6.79]} scale={0.648} />
      
      <group position={[0, 0, -0.973]}>
        <mesh geometry={nodes.Plane018.geometry} material={materials.cardboard} />
        <mesh geometry={nodes.Plane018_1.geometry} material={materials.tv} />
      </group>
      <mesh geometry={nodes['35Macetas001'].geometry} material={materials['Material.007']} />
      <group position={[3.089, -1.744, 1.008]} rotation={[-0.01, 0.009, 0.134]} scale={[1.094, 0.671, 1.1]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials.cardboard} />
      </group>
      
      {/* 🌌 NUBES (Se mantienen visibles) */}
      <mesh geometry={nodes.nube_1.geometry} material={materials['Material.026']} position={[3.256, 4.141, -5.671]} rotation={[Math.PI / 2, 0, 0]} scale={[2.177, 2.177, 1.36]} />
      <mesh geometry={nodes.nube_1001.geometry} material={materials['Material.026']} position={[-4.739, 3.087, -5.007]} rotation={[Math.PI / 2, 0, 0]} scale={[2.883, 2.883, 1.801]} />
      
      <group position={[0, 0, -1.528]}>
        <mesh geometry={nodes.Plane023.geometry} material={materials.cardboard} />
        <mesh geometry={nodes.Plane023_1.geometry} material={materials['comedor.001']} />
      </group>
      <mesh geometry={nodes.luz.geometry} material={materials.luz} position={[0, 0, -3.13]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-1.876, -0.214, -3.229]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane025.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane025_1.geometry} material={materials['Material.011']} />
      </group>
      <group position={[0, 0, -1.837]}>
        <mesh geometry={nodes.Plane026.geometry} material={materials.cardboard} />
        <mesh geometry={nodes.Plane026_1.geometry} material={materials['comedor.001']} />
      </group>
      
      //muñeca
      <group position={[0.109, 1.82, -4.39]} rotation={[1.55, -0.178, -0.013]} scale={0.447}>
        <mesh geometry={nodes.Plane027.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Plane027_1.geometry} material={materials['Material.009']} />
      </group>
       
      {/* 🎯 VITRINA FRONTAL (Elemento desencadenante del Clic) */}
      <mesh 
        geometry={nodes.vitrina_frontal.geometry} 
        material={materials['Material.003']} 
        position={[-0.063, 0.578, -4.418]} 
        rotation={[Math.PI / 2, 0, 0]} 
        scale={[1.051, 1.473, 1.473]} 
        onClick={handleClick}
        onPointerOver={handlePointerOver}
        onPointerOut={handlePointerOut}
      />

      <group position={[-0.066, 0.544, -4.483]} rotation={[Math.PI / 2, 0, 0]} scale={[1.051, 1.473, 1.473]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.008']} />
      </group>
      
      <mesh geometry={nodes.fondo.geometry} material={materials['Material.013']} position={[-0.06, 0.544, -4.53]} rotation={[Math.PI / 2, 0, 0]} scale={[1.162, 1.628, 1.628]} />
    </group>
  )
}

useGLTF.preload('/models/CasaEscenario.glb')