/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/galeria.glb 
*/

import React, { useState, useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/galeria.glb')

  const [fadeOverlay, setFadeOverlay] = useState(true)
  const overlayRef = useRef()

  useEffect(() => {
    document.body.style.cursor = 'auto'
    // Limpieza de seguridad al desmontar la galería
    return () => {
      document.body.style.cursor = 'auto'
    }
  }, [])

  useFrame((state, delta) => {
    if (fadeOverlay && overlayRef.current) {
      overlayRef.current.material.opacity = THREE.MathUtils.lerp(overlayRef.current.material.opacity, 0, 2 * delta)
      
      overlayRef.current.position.copy(state.camera.position)
      const dir = new THREE.Vector3()
      state.camera.getWorldDirection(dir)
      overlayRef.current.position.addScaledVector(dir, 0.2) 
      overlayRef.current.lookAt(state.camera.position)

      if (overlayRef.current.material.opacity < 0.01) {
        setFadeOverlay(false)
      }
    }
  })

  // 🟦 NUEVO 2: Funciones manejadoras de los objetos interactivos
  const handlePointerOver = (e) => {
    e.stopPropagation() // Evita que el evento traspase a objetos detrás
    document.body.style.cursor = 'pointer'
  }

  const handlePointerOut = (e) => {
    e.stopPropagation()
    document.body.style.cursor = 'auto'
  }

  const handleItemClick = (e, nombreItem) => {
    e.stopPropagation()
    console.log(`¡Hiciste click en: ${nombreItem}!`)
    
    // Aquí puedes agregar la lógica que quieras que suceda al dar click (abrir modals, mover la cámara, etc)
    if (nombreItem.includes('bici')) {
      // Lógica de la bici
    } else if (nombreItem.includes('mapa')) {
      // Lógica del mapa
    }
  }

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane002.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane006.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane013.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane013_1.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane017.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane017_1.geometry} material={materials['Material.007']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane019.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane019_1.geometry} material={materials['Material.007']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane021.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane021_1.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-1.419, 1.744, 5.323]} rotation={[Math.PI / 2, 0, 2.77]} scale={[0.128, 0.455, 0.272]}>
          <mesh geometry={nodes.Quad_Sphere011.geometry} material={materials['Cardboard.003']} />
          <mesh geometry={nodes.Quad_Sphere011_1.geometry} material={materials['Cardboard.004']} />
          <mesh geometry={nodes.Quad_Sphere011_2.geometry} material={materials['Damaged Cardboard.002']} />
        </group>
        <mesh geometry={nodes.PISO.geometry} material={materials['Material.008']} position={[-1.095, -18.71, 0]} />
        <mesh geometry={nodes.PARED.geometry} material={materials['Material.010']} position={[-1.095, -18.71, 0]} />
        <mesh geometry={nodes.TECHO.geometry} material={materials['Material.015']} position={[-1.095, -18.71, 0]} />
        <mesh geometry={nodes.RAYPO_CORPUSCULAR_2.geometry} material={materials['Material.016']} position={[-1.095, -18.71, 0]} />
        <mesh geometry={nodes.RAYO_CORPUSCULAR_1.geometry} material={materials['Material.016']} position={[-1.095, -18.71, 0]} />
        
        {/* 🟦 SOLAMENTE LA BICI ES INTERACTIVA */}
        <mesh 
          geometry={nodes.BICI.geometry} 
          material={materials['Material.027']} 
          position={[4.099, 3.94, 3.965]} 
          rotation={[Math.PI / 2, 0, -0.85]} 
          scale={1.576} 
          onPointerOver={handlePointerOver}
          onPointerOut={handlePointerOut}
          onClick={(e) => handleItemClick(e, 'bici')}
        />
        
        {/* 🟦 SOLAMENTE EL MAPA ES INTERACTIVO */}
        <mesh 
          geometry={nodes.MAPA.geometry} 
          material={materials['Material.029']} 
          position={[-5.418, 3.717, 4.537]} 
          rotation={[Math.PI / 2, 0, 0.712]} 
          scale={[1.037, 0.755, 1.576]} 
          onPointerOver={handlePointerOver}
          onPointerOut={handlePointerOut}
          onClick={(e) => handleItemClick(e, 'mapa')}
        />
      </group>

      {/* 🟦 CORTINA AZUL (Se añade al final para que no sea afectada por las rotaciones de los grupos internos) */}
      {fadeOverlay && (
        <mesh ref={overlayRef}>
          <planeGeometry args={[2, 2]} />
          <meshBasicMaterial 
            color="#1e293b" 
            transparent 
            opacity={1} 
            side={THREE.DoubleSide} 
            depthTest={false} 
          />
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload('/models/galeria.glb')