/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/galeria.glb 
*/

import React, { useState, useRef, useEffect, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/galeria.glb')
  const { camera } = useThree()

  const [fadeOverlay, setFadeOverlay] = useState(true)
  const overlayRef = useRef()

  // ─────────────────────────────────────────────────────────
  // 🟦 ESTADOS DEL MAPA (PUZZLE 1)
  // ─────────────────────────────────────────────────────────
  const MAPA_INITIAL_POSITION = [-5.418, 3.717, 4.537]
  const [mapaPosition, setMapaPosition] = useState(MAPA_INITIAL_POSITION)

  const OBJETIVO_MAPA = new THREE.Vector3(-1.773, 1.504, 7.218) 
  const TOLERANCIA_OBJETIVO = 15.8 
  
  const isReturningMapa = useRef(false) 
  const isDraggingMapa = useRef(false)
  const [mapaSolved, setMapaSolved] = useState(false) 

  const isBicicletoInFloor = useRef(false) 

  const mapaParentRef = useRef()
  const dragPlane = useRef(new THREE.Plane())
  const dragOffset = useRef(new THREE.Vector3())

  // ─────────────────────────────────────────────────────────
  // 🟦 ESTADOS DE LA BICI GRANDE (PUZZLE 2)
  // ─────────────────────────────────────────────────────────
  const BICI_INITIAL_POS_ARR = [4.099, 3.94, 3.965]
  const [biciPosition, setBiciPosition] = useState(BICI_INITIAL_POS_ARR)
  const [biciSolved, setBiciSolved] = useState(false)

  const isDraggingBici = useRef(false)
  const isReturningBici = useRef(false)
  
  const biciDragPlane = useRef(new THREE.Plane())
  const biciDragOffset = useRef(new THREE.Vector3())
  const TOLERANCIA_OBJETIVO_BICI = 15.8 

  // ─────────────────────────────────────────────────────────
  // 🟦 ESTADOS DE CINEMÁTICA FINAL
  // ─────────────────────────────────────────────────────────
  const [cinematicStarted, setCinematicStarted] = useState(false)
  const cardboardOverlayRef = useRef()

  // ─────────────────────────────────────────────────────────
  // 🟦 REFERENCIAS DE ANIMACIÓN
  // ─────────────────────────────────────────────────────────
  const bicicletoRef = useRef()
  const mapaMeshRef = useRef()
  const biciRef = useRef() 
  const biciOcultaRef = useRef() // <--- REFERENCIA NUEVA AÑADIDA

  const BICICLETO_INITIAL_POS = useMemo(() => new THREE.Vector3(-1.773, 1.504, 7.218), [])
  const BICICLETO_FLOOR_POS = useMemo(() => new THREE.Vector3(-1.773, 0.71, 7.218), []) 
  const BICI_INITIAL_POS = useMemo(() => new THREE.Vector3(...BICI_INITIAL_POS_ARR), [])

  useEffect(() => {
    document.body.style.cursor = 'auto'
    return () => { document.body.style.cursor = 'auto' }
  }, [])

  useFrame((state, delta) => {
    const time = state.clock.getElapsedTime()

    // 1. Efecto Fade de inicio
    if (fadeOverlay && overlayRef.current) {
      overlayRef.current.material.opacity = THREE.MathUtils.lerp(overlayRef.current.material.opacity, 0, 2 * delta)
      overlayRef.current.position.copy(state.camera.position)
      const dir = new THREE.Vector3()
      state.camera.getWorldDirection(dir)
      overlayRef.current.position.addScaledVector(dir, 0.2) 
      overlayRef.current.lookAt(state.camera.position)

      if (overlayRef.current.material.opacity < 0.01) setFadeOverlay(false)
    }

    // 2. Retorno suave del mapa si falla
    if (isReturningMapa.current && !mapaSolved) {
      setMapaPosition((prevPos) => {
        const current = new THREE.Vector3(...prevPos)
        const origin = new THREE.Vector3(...MAPA_INITIAL_POSITION)
        current.lerp(origin, 5 * delta) 
        if (current.distanceTo(origin) < 0.05) {
          isReturningMapa.current = false
          return MAPA_INITIAL_POSITION
        }
        return [current.x, current.y, current.z]
      })
    }

    // 3. Secuencia de Victoria del Mapa
    if (mapaSolved) {
      if (mapaMeshRef.current && bicicletoRef.current) {
        mapaMeshRef.current.position.lerp(bicicletoRef.current.position, 5 * delta)
        mapaMeshRef.current.scale.lerp(new THREE.Vector3(0, 0, 0), 3 * delta)
      }
      if (bicicletoRef.current && !cinematicStarted) {
        bicicletoRef.current.position.lerp(BICICLETO_FLOOR_POS, 2 * delta)
        if (bicicletoRef.current.position.distanceTo(BICICLETO_FLOOR_POS) < 0.5) {
          isBicicletoInFloor.current = true
        }
      }
    }

    // 4. Temblor del Bicicleto al arrastrar (solo si no has ganado el mapa)
    if (bicicletoRef.current && !mapaSolved) {
      if (isDraggingMapa.current) {
        const shakeX = Math.sin(time * 30) * 0.05
        const shakeZ = Math.cos(time * 35) * 0.05
        bicicletoRef.current.position.x = BICICLETO_INITIAL_POS.x + shakeX
        bicicletoRef.current.position.z = BICICLETO_INITIAL_POS.z + shakeZ
      } else {
        bicicletoRef.current.position.lerp(BICICLETO_INITIAL_POS, 5 * delta)
      }
    }

    // 5. Lógica Completa de la Bici Grande (PUZZLE 2)
    if (biciSolved) {
      // Bici absorbida
      if (biciRef.current && bicicletoRef.current) {
        biciRef.current.position.lerp(bicicletoRef.current.position, 5 * delta)
        biciRef.current.scale.lerp(new THREE.Vector3(0, 0, 0), 3 * delta)
      }
    } else if (isBicicletoInFloor.current) {
      if (isDraggingBici.current) {
        // Nada extra, render actualiza su posición
      } else if (isReturningBici.current) {
        // Regreso suave si falla
        setBiciPosition((prevPos) => {
          const current = new THREE.Vector3(...prevPos)
          const origin = BICI_INITIAL_POS
          current.lerp(origin, 5 * delta)
          if (current.distanceTo(origin) < 0.05) {
            isReturningBici.current = false
            return BICI_INITIAL_POS_ARR
          }
          return [current.x, current.y, current.z]
        })
      } else {
        // Temblor pidiendo ser arrastrada
        const shakeX = Math.sin(time * 40) * 0.08
        const shakeZ = Math.cos(time * 45) * 0.08
        if (biciRef.current) {
          biciRef.current.position.x = BICI_INITIAL_POS.x + shakeX
          biciRef.current.position.y = BICI_INITIAL_POS.y
          biciRef.current.position.z = BICI_INITIAL_POS.z + shakeZ
        }
      }
    }

   // 6. 🎬 CINEMÁTICA FINAL: Movimiento diagonal y textura de cartón
    if (cinematicStarted) {
      // 🚴‍♂️ Velocidad y dirección del movimiento diagonal (hacia el fondo)
      const speedX = .84; 
      const speedZ = -15; // Valor negativo para alejarlo de la cámara
      
      // ==========================================
      // 1️⃣ FASE 1: MOVER A LOS PERSONAJES
      // ==========================================
      
      // Movemos el Bicicleto2
      if (bicicletoRef.current) {
        bicicletoRef.current.position.x += speedX * delta;
        bicicletoRef.current.position.z += speedZ * delta;
      }
      
      // Movemos la Bicicleta Oculta a la misma velocidad
      if (biciOcultaRef.current) {
        biciOcultaRef.current.position.x += speedX * delta;
        biciOcultaRef.current.position.z += speedZ * delta;
      }

      // 🛑 Calculamos si el monito ya llegó a su destino (ajusta el -15 según tu escena)
      const haTerminadoRecorrido = bicicletoRef.current && bicicletoRef.current.position.z <= -15;

      // ==========================================
      // 2️⃣ FASE 2: ANIMACIÓN DEL CARTÓN
      // ==========================================
      
      // Solo entra aquí si el monito ya pasó de la marca Z = -15
      if (haTerminadoRecorrido && cardboardOverlayRef.current) {
        const camPos = state.camera.position;
        const camDir = new THREE.Vector3();
        state.camera.getWorldDirection(camDir);

        // Posicionamos el cartón justo frente a la cámara
        cardboardOverlayRef.current.position.copy(camPos);
        cardboardOverlayRef.current.position.addScaledVector(camDir, 0.3); 
        cardboardOverlayRef.current.lookAt(camPos);
        
        // Aumentamos la opacidad suavemente (Fade-in)
        cardboardOverlayRef.current.material.opacity = THREE.MathUtils.lerp(
          cardboardOverlayRef.current.material.opacity, 
          1, 
          1.5 * delta
        );
      }
    }
  })

  // ── Handlers de arrastre del MAPA ────────────────
  const handleMapaPointerOver = (e) => {
    e.stopPropagation()
    if (!isDraggingMapa.current && !mapaSolved) document.body.style.cursor = 'grab'
  }
  const handleMapaPointerOut = (e) => {
    e.stopPropagation()
    if (!isDraggingMapa.current) document.body.style.cursor = 'auto'
  }
  const handleMapaPointerDown = (e) => {
    e.stopPropagation()
    if (mapaSolved) return 
    e.target.setPointerCapture(e.pointerId)
    isDraggingMapa.current = true
    isReturningMapa.current = false 
    document.body.style.cursor = 'grabbing'
    if (!mapaParentRef.current) return
    const normal = new THREE.Vector3()
    camera.getWorldDirection(normal)
    dragPlane.current.setFromNormalAndCoplanarPoint(normal, e.point)
    const localPoint = mapaParentRef.current.worldToLocal(e.point.clone())
    dragOffset.current.copy(localPoint).sub(new THREE.Vector3(...mapaPosition))
  }
  const handleMapaPointerMove = (e) => {
    if (!isDraggingMapa.current || !mapaParentRef.current || mapaSolved) return
    e.stopPropagation()
    const worldPoint = new THREE.Vector3()
    if (e.ray.intersectPlane(dragPlane.current, worldPoint)) {
      const localPoint = mapaParentRef.current.worldToLocal(worldPoint.clone())
      localPoint.sub(dragOffset.current)
      setMapaPosition([localPoint.x, localPoint.y, localPoint.z])
    }
  }
  const handleMapaPointerUp = (e) => {
    e.stopPropagation()
    if (mapaSolved) return
    e.target.releasePointerCapture(e.pointerId)
    isDraggingMapa.current = false
    document.body.style.cursor = 'auto'
    const posicionActual = new THREE.Vector3(...mapaPosition)
    const dx = posicionActual.x - OBJETIVO_MAPA.x
    const dy = posicionActual.y - OBJETIVO_MAPA.y
    const distancia2D = Math.sqrt(dx * dx + dy * dy)
    if (distancia2D <= TOLERANCIA_OBJETIVO) {
      setMapaSolved(true) 
    } else {
      isReturningMapa.current = true 
    }
  }

  // ── Handlers de arrastre de la BICI ───────
  const handleBiciPointerOver = (e) => {
    e.stopPropagation()
    if (isBicicletoInFloor.current && !isDraggingBici.current && !biciSolved) {
      document.body.style.cursor = 'grab'
    }
  }
  const handleBiciPointerOut = (e) => {
    e.stopPropagation()
    if (!isDraggingBici.current) document.body.style.cursor = 'auto'
  }
  const handleBiciPointerDown = (e) => {
    e.stopPropagation()
    if (!isBicicletoInFloor.current || biciSolved) return 
    
    e.target.setPointerCapture(e.pointerId)
    isDraggingBici.current = true
    isReturningBici.current = false
    document.body.style.cursor = 'grabbing'
    
    if (!mapaParentRef.current) return
    const normal = new THREE.Vector3()
    camera.getWorldDirection(normal)
    biciDragPlane.current.setFromNormalAndCoplanarPoint(normal, e.point)
    const localPoint = mapaParentRef.current.worldToLocal(e.point.clone())
    biciDragOffset.current.copy(localPoint).sub(new THREE.Vector3(...biciPosition))
  }
  const handleBiciPointerMove = (e) => {
    if (!isDraggingBici.current || !mapaParentRef.current || biciSolved) return
    e.stopPropagation()
    const worldPoint = new THREE.Vector3()
    if (e.ray.intersectPlane(biciDragPlane.current, worldPoint)) {
      const localPoint = mapaParentRef.current.worldToLocal(worldPoint.clone())
      localPoint.sub(biciDragOffset.current)
      setBiciPosition([localPoint.x, localPoint.y, localPoint.z])
    }
  }
  const handleBiciPointerUp = (e) => {
    e.stopPropagation()
    if (!isDraggingBici.current || biciSolved) return
    
    e.target.releasePointerCapture(e.pointerId)
    isDraggingBici.current = false
    document.body.style.cursor = 'auto'

    const posicionActual = new THREE.Vector3(...biciPosition)
    
    const dx = posicionActual.x - bicicletoRef.current.position.x
    const dy = posicionActual.y - bicicletoRef.current.position.y
    const distancia2D = Math.sqrt(dx * dx + dy * dy)

    if (distancia2D <= TOLERANCIA_OBJETIVO_BICI) {
      console.log("¡Fusionados!")
      setBiciSolved(true) 

      // 🎬 Dispara la cinemática después de 1.2 segundos
      setTimeout(() => {
        setCinematicStarted(true)
      }, 1200)

    } else {
      console.log("Fallaste. Regresando bici...")
      isReturningBici.current = true 
    }
  }

  return (
    <group {...props} dispose={null}>
      <group ref={mapaParentRef}>
        {/* GEOMETRÍAS ESTÁTICAS */}
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane002.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.006']} />
        </group>
        <mesh geometry={nodes.PISO.geometry} material={materials['Material.008']} position={[-1.095, -18.71, 0]} />
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane006.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.009']} />
        </group>
        <mesh geometry={nodes.PARED.geometry} material={materials['Material.010']} position={[-1.095, -18.71, 0]} />
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane013.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane013_1.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane017.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane017_1.geometry} material={materials['Material.007']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane019.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane019_1.geometry} material={materials['Material.007']} />
        </group>
        <group position={[-1.095, -18.71, 0]}>
          <mesh geometry={nodes.Plane021.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Plane021_1.geometry} material={materials['Material.004']} />
        </group>

        <mesh geometry={nodes.TECHO.geometry} material={materials['Material.015']} position={[-1.095, -18.71, 0]} />
        <mesh geometry={nodes.RAYPO_CORPUSCULAR_2.geometry} material={materials['Material.016']} position={[-1.095, -18.71, 0]} />
        <mesh geometry={nodes.RAYO_CORPUSCULAR_1.geometry} material={materials['Material.016']} position={[-1.095, -18.71, 0]} />
        
        {/* BICICLETA OCULTA */}
        <group 
          ref={biciOcultaRef} 
          visible={biciSolved} 
          position={[-0.988, 2.244, 7.648]} 
          rotation={[Math.PI / 2, 0, 2.983]} 
          scale={0.631}
        >
          <mesh geometry={nodes.Tube_17001.geometry} material={materials['Cardboard.001']} />
          <mesh geometry={nodes.Tube_17001_1.geometry} material={materials['Damaged Cardboard.001']} />
          <mesh geometry={nodes.Tube_17001_2.geometry} material={materials['Cardboard.002']} />
        </group>

        {/* CUERPO BICICLETO */}
        <group ref={bicicletoRef} position={[-1.773, 1.504, 7.218]} rotation={[Math.PI / 2, 0, 2.983]} scale={[0.166, 0.589, 0.352]}>
          <mesh geometry={nodes.Quad_Sphere001.geometry} material={materials['Cardboard.002']} />
          <mesh geometry={nodes.Quad_Sphere001_1.geometry} material={materials['Cardboard.001']} />
        </group>

        {/* LA BICI GRANDE */}
        <mesh 
          ref={biciRef}
          geometry={nodes.BICI.geometry} 
          material={materials['Material.027']} 
          position={biciPosition} 
          rotation={[Math.PI / 2, 0, -0.85]} 
          scale={[1.576, 1.576, 1.576]} 
          onPointerOver={handleBiciPointerOver}
          onPointerOut={handleBiciPointerOut}
          onPointerDown={handleBiciPointerDown}
          onPointerMove={handleBiciPointerMove}
          onPointerUp={handleBiciPointerUp}
        />
        
        {/* EL MAPA ARRASTRABLE */}
        <mesh 
          ref={mapaMeshRef}
          geometry={nodes.MAPA.geometry} 
          material={materials['Material.029']} 
          position={mapaPosition} 
          rotation={[Math.PI / 2, 0, 0.712]} 
          scale={[1.037, 0.755, 1.576]} 
          onPointerOver={handleMapaPointerOver}
          onPointerOut={handleMapaPointerOut}
          onPointerDown={handleMapaPointerDown}
          onPointerMove={handleMapaPointerMove}
          onPointerUp={handleMapaPointerUp}
        />
      </group>

      {/* 🎬 PLANO DE TRANSICIÓN FINAL (Textura Cartón) */}
      {cinematicStarted && (
        <mesh ref={cardboardOverlayRef}>
          <planeGeometry args={[10, 10]} />
          <meshBasicMaterial 
            color={materials['Cardboard.002'].color}
            map={materials['Cardboard.002'].map} 
            transparent 
            opacity={0} 
            side={THREE.DoubleSide} 
            depthTest={false} 
          />
        </mesh>
      )}

      {/* CORTINA AZUL DE CARGA (Inicio) */}
      {fadeOverlay && (
        <mesh ref={overlayRef}>
          <planeGeometry args={[2, 2]} />
          <meshBasicMaterial 
            color="#1e293b" 
            transparent 
            opacity={1} 
            side={THREE.DoubleSide} 
            depthTest={false} 
          />
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload('/models/galeria.glb')