/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/eliassanchez/Desarrollo/hackaton/r3f-baking/public/models/Living room_Baked.glb 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function LivingRoom(props) {
  const { nodes, materials } = useGLTF('/models/Living room_Baked.glb')
  
  // Referencia y estado para la animación del cojín
  const pillowRef = useRef()
  const [isFalling, setIsFalling] = useState(false)

  // Animación continua (60 FPS)
  useFrame((state, delta) => {
    if (!pillowRef.current) return;

    if (isFalling) {
      // CAE AL SUELO: Movemos hacia abajo (Y: 0.05) y rotamos de lado (Z: -90 grados)
      pillowRef.current.position.y = THREE.MathUtils.lerp(pillowRef.current.position.y, 0.05, 5 * delta)
      pillowRef.current.rotation.z = THREE.MathUtils.lerp(pillowRef.current.rotation.z, -Math.PI / 2, 5 * delta)
    } else {
      // REGRESA A LA NORMALIDAD: Volvemos a la altura original (Y: 0.155) y rotación original (Z: 0)
      pillowRef.current.position.y = THREE.MathUtils.lerp(pillowRef.current.position.y, 0.155, 5 * delta)
      pillowRef.current.rotation.z = THREE.MathUtils.lerp(pillowRef.current.rotation.z, 0, 5 * delta)
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BG_Baked.geometry} material={materials.Bake_BG_Baked} position={[0, 0.045, 0]} scale={1.54} />
      <mesh geometry={nodes.Frame_Baked.geometry} material={materials['Bake_Walls_Baked.006']} position={[0.057, 0.356, -0.257]} rotation={[Math.PI / 2, 0, 0]} scale={[0.818, 1, 1.279]} />
      <mesh geometry={nodes.Painting001_Baked.geometry} material={materials['Bake_Walls_Baked.006']} position={[0.057, 0.356, -0.257]} rotation={[Math.PI / 2, 0, 0]} scale={[0.818, 1, 1.279]} />
      <mesh geometry={nodes.Floor_Baked.geometry} material={materials['Bake_Walls_Baked.006']} />
      <mesh geometry={nodes.Wall_Baked.geometry} material={materials['Bake_Walls_Baked.006']} />
      <mesh geometry={nodes.Wall002_Baked.geometry} material={materials['Bake_Walls_Baked.006']} />
      <mesh geometry={nodes.Sofa002_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.202, 0.149, 0.046]} />
      <mesh geometry={nodes.Pillow004_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.23, 0.164, 0.046]} rotation={[-1.487, 1.279, 1.483]} />
      <mesh geometry={nodes.Pillow005_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.197, 0.18, 0.045]} rotation={[0, 0.043, -Math.PI / 2]} />
      <mesh geometry={nodes.Rug_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[0.115, 0.091, 0.055]} />
      <mesh geometry={nodes.Table_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[0.086, 0.117, 0.053]} rotation={[0, 0.484, 0]} />

      <mesh geometry={nodes.Sofa_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[0.058, 0.143, -0.174]} />

      <mesh geometry={nodes.Pillow002_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.025, 0.173, -0.16]} rotation={[0, -0.628, -Math.PI / 2]} />
      <mesh geometry={nodes.Pillow003_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[0.149, 0.172, -0.139]} rotation={[-Math.PI, 0.157, Math.PI / 2]} />
      <mesh geometry={nodes.Pillow001_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[0.018, 0.155, -0.203]} rotation={[-0.291, 0, 0]} />
      
      {/* Cojín interactivo que se cae, abre Facebook y regresa */}
      <mesh 
        ref={pillowRef}
        geometry={nodes.Pillow_Baked.geometry} 
        material={materials['Bake_Objects_Baked.003']} 
        // Esta posición inicial ahora también sirve como punto de retorno
        position={[0.115, 0.155, -0.203]} 
        rotation={[-0.291, 0, 0]} 
        onClick={(e) => {
          e.stopPropagation();
          
          // Si ya está cayendo, ignoramos clics adicionales para no reiniciar los tiempos
          if (isFalling) return; 

          setIsFalling(true); 
          
          // Abre Facebook después de 700ms
          setTimeout(() => {
            window.open('https://www.facebook.com', '_blank');
            
            // Y 2.5 segundos DESPUÉS de abrir Facebook, el cojín regresa a su lugar
            setTimeout(() => {
              setIsFalling(false);
            }, 2500);

          }, 700);
        }}
        onPointerOver={(e) => {
          e.stopPropagation();
          document.body.style.cursor = 'pointer';
        }}
        onPointerOut={(e) => {
          document.body.style.cursor = 'auto';
        }}
      />
      
      <mesh geometry={nodes.Chair_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.176, 0.212, -0.146]} rotation={[0, 0.168, 0]} />
      <mesh geometry={nodes.Pot_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.173, 0.215, -0.144]} />
      <mesh geometry={nodes.Lamp_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.169, 0.38, -0.257]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Window001_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.267, 0.427, -0.042]} />
      <mesh geometry={nodes.Curtains_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.258, 0.427, -0.042]} />
      <mesh geometry={nodes.Window_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.276, 0.356, -0.049]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Sofa_legs_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.117, 0.109, -0.017]} />
      <mesh geometry={nodes.Sofa001_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.237, 0.087, 0.088]} />
      <mesh geometry={nodes.Table001_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[0.127, 0.111, 0.045]} rotation={[0, 0.484, 0]} />
      <mesh geometry={nodes.Sofa_legs001_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[0.169, 0.106, -0.118]} />
      <mesh geometry={nodes.Sofa003_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.042, 0.068, -0.234]} />
      <mesh geometry={nodes.Chair001_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.19, 0.195, -0.128]} rotation={[0, -0.217, 0]} />
      <mesh geometry={nodes.Chair002_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.175, 0.151, -0.147]} />
      <mesh geometry={nodes.Plant_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.173, 0.234, -0.144]} rotation={[-2.993, -0.059, -2.786]} />
      <mesh geometry={nodes.Light_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.167, 0.348, -0.217]} />
      <mesh geometry={nodes.Lamp001_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.169, 0.38, -0.257]} />
      <mesh geometry={nodes.Window002_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.262, 0.418, 0.063]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Window003_Baked.geometry} material={materials['Bake_Objects_Baked.003']} position={[-0.257, 0.427, 0.087]} />
    </group>
  )
}

useGLTF.preload('/models/Living room_Baked.glb')