/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mapa.glb 
*/

import React, { useRef, useMemo, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'

export function Model({ onReachPoint1, onTransitionEnd, ...props }) {
  const { nodes, materials } = useGLTF('/models/mapa.glb')
  const { camera } = useThree()

  // ─────────────────────────────────────────────────────────
  // 🧲 REFERENCIAS Y ESTADOS DE SECUENCIA
  // ─────────────────────────────────────────────────────────
  const mapaGroupRef = useRef()
  const calacoRef = useRef()
  const manoRef = useRef()

  const [sequencePhase, setSequencePhase] = useState('playing') 

  const IMAN_1 = useMemo(() => new THREE.Vector3(0.042, 2.56, 3.296), [])
  const IMAN_2 = useMemo(() => new THREE.Vector3(0.029, 3.19, 0.218), [])
  const ALTURA_SEGURA = 3.38

  const isDragging = useRef(false)
  const targetPos = useRef(new THREE.Vector3(0.486, ALTURA_SEGURA, -0.265))
  const dragPlane = useRef(new THREE.Plane())
  const dragOffset = useRef(new THREE.Vector3())

  useEffect(() => {
    document.body.style.cursor = 'auto'
    return () => { document.body.style.cursor = 'auto' }
  }, [])

  // ─────────────────────────────────────────────────────────
  // ⚙️ MOTOR DE FÍSICAS Y CINEMÁTICA
  // ─────────────────────────────────────────────────────────
  useFrame((state, delta) => {
    if (!calacoRef.current) return

    // 🕹️ FASE 1: JUGANDO 
    if (sequencePhase === 'playing') {
      const iman1_plano = new THREE.Vector3(IMAN_1.x, ALTURA_SEGURA, IMAN_1.z)
      const iman2_plano = new THREE.Vector3(IMAN_2.x, ALTURA_SEGURA, IMAN_2.z)

      if (isDragging.current) {
        const posicionMouse = targetPos.current.clone()
        const vectorAtraccion = new THREE.Vector3().subVectors(iman1_plano, posicionMouse)
        vectorAtraccion.multiplyScalar(0.15) 
        
        posicionMouse.add(vectorAtraccion)
        posicionMouse.y = ALTURA_SEGURA 
        calacoRef.current.position.lerp(posicionMouse, 15 * delta)

      } else {
        const dist1 = calacoRef.current.position.distanceTo(iman1_plano)
        const dist2 = calacoRef.current.position.distanceTo(iman2_plano)

        if (dist1 < 1.2) {
          calacoRef.current.position.lerp(iman1_plano, 8 * delta)
          // 🎯 LLEGÓ AL IMÁN 1
          if (dist1 < 0.2) {
            setSequencePhase('hand_entering') 
            if (onReachPoint1) onReachPoint1() // Desata la casa y la cámara en Experience
          }
        } else if (dist2 < 1.2) {
          calacoRef.current.position.lerp(iman2_plano, 8 * delta)
        } else {
          calacoRef.current.position.y = ALTURA_SEGURA
        }
      }
    }

    // 🖐️ FASE 2: ENTRA LA MANO (Desde la izquierda)
    if (sequencePhase === 'hand_entering' && manoRef.current) {
      manoRef.current.visible = true
      // Viene desde -15 hacia su posición para "agarrar"
      manoRef.current.position.x = THREE.MathUtils.lerp(manoRef.current.position.x, 0.517, 4 * delta)
      
      if (manoRef.current.position.x > 0.3) {
        setSequencePhase('pulling')
      }
    }

    // 💨 FASE 3: LA MANO JALA EL MAPA (Regresa a la izquierda)
    if (sequencePhase === 'pulling' && mapaGroupRef.current) {
      // El grupo entero se mueve a la izquierda, llevándose la mano con él (ilusión de regresar)
      mapaGroupRef.current.position.x -= 20 * delta 
      
      // Cuando ya salió de la pantalla
      if (mapaGroupRef.current.position.x < -25) {
        if (onTransitionEnd) onTransitionEnd() 
      }
    }
  })

  // ─────────────────────────────────────────────────────────
  // 🖱️ EVENTOS DE DRAG & DROP
  // ─────────────────────────────────────────────────────────
  const handlePointerOver = (e) => {
    e.stopPropagation()
    if (sequencePhase === 'playing' && !isDragging.current) document.body.style.cursor = 'grab'
  }

  const handlePointerOut = (e) => {
    e.stopPropagation()
    if (sequencePhase === 'playing' && !isDragging.current) document.body.style.cursor = 'auto'
  }

  const handlePointerDown = (e) => {
    if (sequencePhase !== 'playing') return
    e.stopPropagation()
    e.target.setPointerCapture(e.pointerId)
    isDragging.current = true
    document.body.style.cursor = 'grabbing'

    if (!mapaGroupRef.current) return

    // Plano de frente a la cámara para evitar que el rayo se vaya al infinito
    const normal = new THREE.Vector3()
    camera.getWorldDirection(normal)
    normal.negate() 
    
    dragPlane.current.setFromNormalAndCoplanarPoint(normal, calacoRef.current.position)

    const localPoint = mapaGroupRef.current.worldToLocal(e.point.clone())
    dragOffset.current.copy(localPoint).sub(calacoRef.current.position)
  }

  const handlePointerMove = (e) => {
    if (!isDragging.current || !mapaGroupRef.current || sequencePhase !== 'playing') return
    e.stopPropagation()

    const worldPoint = new THREE.Vector3()
    if (e.ray.intersectPlane(dragPlane.current, worldPoint)) {
      const localPoint = mapaGroupRef.current.worldToLocal(worldPoint.clone())
      targetPos.current.copy(localPoint).sub(dragOffset.current)
      
      // 🛡️ LIMITES DEL MAPA (Que no se salga ni adelante ni atrás)
      targetPos.current.y = ALTURA_SEGURA 
      
      // Izquierda - Derecha (Ajusta estos si la mesa es más ancha)
      targetPos.current.x = THREE.MathUtils.clamp(targetPos.current.x, -3.0, 3.0) 
      
      // Adelante - Atrás (Ajusta estos si la mesa es más profunda)
      targetPos.current.z = THREE.MathUtils.clamp(targetPos.current.z, -2.0, 4.5) 
    }
  }

  const handlePointerUp = (e) => {
    if (sequencePhase !== 'playing') return
    e.stopPropagation()
    e.target.releasePointerCapture(e.pointerId)
    isDragging.current = false
    document.body.style.cursor = 'auto'
  }

  return (
    <group ref={mapaGroupRef} {...props} dispose={null}>
      <mesh geometry={nodes.mapa.geometry} material={materials['Material.001']} position={[0, 1.996, 0]} scale={1.1} />
      <mesh geometry={nodes.circulo_2.geometry} material={materials['Material.002']} position={[0.029, 3.19, 0.218]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.096} />
      <mesh geometry={nodes.circulo_1.geometry} material={materials['Material.002']} position={[0.042, 2.56, 3.296]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.093} />
      
      <mesh  
        ref={calacoRef}
        geometry={nodes.calaco.geometry}  
        material={materials['Material.003']} 
        position={[0.486, ALTURA_SEGURA, 1.265]} 
        rotation={[1.604, 0.044, -1.623]} 
        scale={[1.38, 0.74, 0.748]} 
        onPointerOver={handlePointerOver}
        onPointerOut={handlePointerOut}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
      />

      {/* MANO GIGANTE */}
      <mesh 
        ref={manoRef}
        visible={false} 
        geometry={nodes.mano.geometry} 
        material={materials['Material.004']} 
        position={[-15, 1.268, 2.836]} // Inicia escondida en X: -15
        rotation={[0.672, -0.027, -1.594]} 
        scale={[1.069, 1.496, 1.498]} 
      />
    </group>
  )
}

useGLTF.preload('/models/mapa.glb')