/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mapa.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/mapa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mapa.geometry} material={materials['Material.001']} position={[0, 1.996, 0]} scale={1.1} />
      <mesh geometry={nodes.circulo_2.geometry} material={materials['Material.002']} position={[0.029, 3.19, 0.218]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.096} />
      <mesh geometry={nodes.circulo_1.geometry} material={materials['Material.002']} position={[0.042, 2.56, 3.296]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.093} />
      <mesh geometry={nodes.calaco.geometry} material={materials['Material.003']} position={[0.186, 2.238, -0.265]} rotation={[1.604, 0.044, -1.623]} scale={[2.525, 1.364, 1.361]} />
      <mesh geometry={nodes.mano.geometry} material={materials['Material.004']} position={[0.517, 1.268, 2.836]} rotation={[0.672, -0.027, -1.594]} scale={[1.069, 1.496, 1.498]} />
    </group>
  )
}

useGLTF.preload('/models/mapa.glb')
