/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/museo.glb 
*/

import React, { useState, useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model({ position = [0, 0, 0], rotation = [0, 0, 0], scale = .5, onEdificioToggle, onFullBlue, ...props }) {
  const { nodes, materials } = useGLTF('/models/museo.glb')
  
  const [mostrarPartes, setMostrarPartes] = useState(false)
  const [mostrarTarjeta, setMostrarTarjeta] = useState(false)
  const [transitionTriggered, setTransitionTriggered] = useState(false)
  const timeoutRef = useRef(null) 

  const pt1Ref = useRef()
  const pt2Ref = useRef()
  const cardRef = useRef() 

  const baseX1 = -1.185
  const baseX2 = -0.185
  const distanciaApertura = 1.5

  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current)
    }
  }, [])

  useFrame((state, delta) => {
    if (mostrarPartes) {
      if (pt1Ref.current) pt1Ref.current.position.x = THREE.MathUtils.lerp(pt1Ref.current.position.x, baseX1 + distanciaApertura, 1.5 * delta)
      if (pt2Ref.current) pt2Ref.current.position.x = THREE.MathUtils.lerp(pt2Ref.current.position.x, baseX2 - distanciaApertura, 1.5 * delta)
    } else {
      if (pt1Ref.current) pt1Ref.current.position.x = THREE.MathUtils.lerp(pt1Ref.current.position.x, baseX1, 1.5 * delta)
      if (pt2Ref.current) pt2Ref.current.position.x = THREE.MathUtils.lerp(pt2Ref.current.position.x, baseX2, 1.5 * delta)
    }

    // ANIMACIÓN DE LA TARJETA (POSICIÓN, OPACIDAD Y ESCALA GIGANTE)
    if (cardRef.current) {
      if (mostrarTarjeta) {
        cardRef.current.position.x = THREE.MathUtils.lerp(cardRef.current.position.x, -1.9, 3 * delta)
        cardRef.current.position.y = THREE.MathUtils.lerp(cardRef.current.position.y, 3.9, 3 * delta)
        cardRef.current.position.z = THREE.MathUtils.lerp(cardRef.current.position.z, -0.5, 3 * delta)
        
        cardRef.current.scale.x = THREE.MathUtils.lerp(cardRef.current.scale.x, 15, 3 * delta)
        cardRef.current.scale.y = THREE.MathUtils.lerp(cardRef.current.scale.y, 15, 3 * delta)
        
        cardRef.current.material.opacity = THREE.MathUtils.lerp(cardRef.current.material.opacity, 1, 3 * delta)

        // DETECTAR CUANDO LA PANTALLA ESTÁ COMPLETAMENTE CUBIERTA
        if (cardRef.current.scale.x > 14 && !transitionTriggered) {
          setTransitionTriggered(true)
          if (onFullBlue) onFullBlue() // Desmonta este componente desde Experience
        }
      } else {
        cardRef.current.position.z = THREE.MathUtils.lerp(cardRef.current.position.z, -5.0, 4 * delta)
        cardRef.current.scale.x = THREE.MathUtils.lerp(cardRef.current.scale.x, 1, 4 * delta)
        cardRef.current.scale.y = THREE.MathUtils.lerp(cardRef.current.scale.y, 1, 4 * delta)
        cardRef.current.material.opacity = THREE.MathUtils.lerp(cardRef.current.material.opacity, 0, 4 * delta)
      }
      
      cardRef.current.lookAt(state.camera.position)
    }
  })

  const handleEdificioClick = (e, abrir) => {
    e.stopPropagation()
    if (e.delta <= 2) {
      if (abrir) {
        setMostrarPartes(true)
        if (onEdificioToggle) onEdificioToggle(true)
        
        if (timeoutRef.current) clearTimeout(timeoutRef.current)
        timeoutRef.current = setTimeout(() => {
          setMostrarTarjeta(true)
        }, 1000) 
      } else {
        setMostrarPartes(false)
        if (onEdificioToggle) onEdificioToggle(false)
        
        if (timeoutRef.current) clearTimeout(timeoutRef.current)
        setMostrarTarjeta(false)
      }
    }
  }

  return (
    <group {...props} dispose={null} position={position} rotation={rotation} scale={scale}>
      
      <group position={[0, 0, -9.454]} rotation={[-Math.PI, -0.016, -Math.PI]}>
        
        <group position={[4.847, 6.386, -6.819]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.215}>
          <mesh geometry={nodes.Plane039.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Plane039_1.geometry} material={materials['carton.001']} />
        </group>
        <group position={[-5.635, 4.77, -6.567]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.911}>
          <mesh geometry={nodes.Plane040.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Plane040_1.geometry} material={materials['carton.001']} />
        </group>
        <group position={[4.408, 3.591, -4.604]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.623}>
          <mesh geometry={nodes.Plane041.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Plane041_1.geometry} material={materials['carton.001']} />
        </group>
        <group position={[-6.408, 3.591, -4.604]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.623}>
          <mesh geometry={nodes.Plane041.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Plane041_1.geometry} material={materials['carton.001']} />
        </group>

        <mesh 
          visible={!mostrarPartes} 
          onClick={(e) => handleEdificioClick(e, true)}
          onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer' }}
          onPointerOut={() => { document.body.style.cursor = 'auto' }}
          geometry={nodes.EdificioCompleto.geometry} 
          material={materials['Material.023']} 
          position={[-1.185, 5.179, -7.246]} 
          rotation={[-Math.PI, 0, -Math.PI]} 
          scale={0.724} 
        />
        
        <mesh geometry={nodes.Fondo.geometry} material={materials['Material.024']} position={[-0.761, 5.34, 0.105]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.878, 0.623, 0.623]} />

        <mesh 
          ref={pt1Ref}
          visible={mostrarPartes} 
          onClick={(e) => handleEdificioClick(e, false)}
          onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer' }}
          onPointerOut={() => { document.body.style.cursor = 'auto' }}
          geometry={nodes.EdificioPT1.geometry} 
          material={materials['Material.023']} 
          position={[-1.185, 5.179, -7.246]} 
          rotation={[-Math.PI, 0, -Math.PI]} 
          scale={0.724} 
        />

        <mesh 
          ref={pt2Ref}
          visible={mostrarPartes} 
          onClick={(e) => handleEdificioClick(e, false)}
          onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer' }}
          onPointerOut={() => { document.body.style.cursor = 'auto' }}
          geometry={nodes.EdificioPT2.geometry} 
          material={materials['Material.023']} 
          position={[-0.185, 5.179, -7.246]} 
          rotation={[-Math.PI, 0, -Math.PI]} 
          scale={0.724} 
        />

        <mesh geometry={nodes.nube_1.geometry} material={materials['Material.026']} position={[3.397, 8.158, -1.483]} rotation={[Math.PI / 2, 0, 0]} scale={[2.883, 2.883, 1.801]} />
        <mesh geometry={nodes.nube_2.geometry} material={materials['Material.026']} position={[4.935, 8.616, -0.376]} rotation={[Math.PI / 2, 0, 0]} scale={[2.491, 2.491, 1.556]} />
        <mesh geometry={nodes.nube_3.geometry} material={materials['Material.026']} position={[-6.854, 6.662, -4.606]} rotation={[Math.PI / 2, 0, 0]} scale={[1.977, 1.977, 1.235]} />
        <mesh geometry={nodes.nube_4.geometry} material={materials['Material.026']} position={[-6.854, 7.324, -3.77]} rotation={[Math.PI / 2, 0, 0]} scale={[3.257, 3.257, 2.035]} />
        <mesh geometry={nodes.RAYO_CORPUSCULAR_1001.geometry} material={materials['Material.016']} position={[-5.158, 5.246, -5.373]} rotation={[Math.PI, 0, 2.884]} scale={[1.289, 2.346, 1.289]} />
      </group>

      <mesh ref={cardRef} position={[-1.72, 3.88, -5.0]}>
        <planeGeometry args={[1.5, 2.5]} /> 
        <meshBasicMaterial color="#1e293b" transparent opacity={0} side={THREE.DoubleSide} depthTest={false} />
      </mesh>

    </group>
  )
}

useGLTF.preload('/models/museo.glb')